
appName: "be-argocd"

replicaCount: 1

image:
  tag: "ecdc317f5649e29f3362fb847fd8548a02bc1fec"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

env:
  ENVIRONMENT: "sandbox"
  LOG_LEVEL: "debug"
  DEBUG_MODE: "true"
